
# Important Notice
#
# This file is managed by Tompero’s indexing process.
# Manual changes to the managed fields won’t take effect and will be overwritted by Tompero.
#
# Tompero will also push commits directly to this file when needed
# without previous Notice. 
# Currently, the fields managed by Tompero are the following:
# * requiredForDR 

apiVersion: ifood/v2
kind: Repository
tags: []
metadata:
  costCenter: antifraud
  tribe: antifraud
  squad: antifraud
  team:
    alias: none
    channel: antifraud
    email: javier.olivella@ifood.com.co
    owner: javier.olivella
spec:
  contents:
    - name: co-aldrin
      description: Model Chargebacks antifraud
      type: other
      subType:
        - cronjob
      impactLevel: 4
      links: []
      deployment:
        type: none
        chefRole: ''
      certifications: []
      ownerLayerSlug: antifraud-int
